name: 'Setup pbuilder'
description: 'Setup the pbuilder environment'

runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update -y
        sudo apt install -y pbuilder debian-archive-keyring

    - shell: bash
      run: |
        sudo touch /root/.pbuilderrc

    - shell: bash
      run: |
        cat <<EOF | sudo tee -a /etc/pbuilderrc >> /dev/null
        PBUILDERSATISFYDEPENDSCMD="/usr/lib/pbuilder/pbuilder-satisfydepends-apt"
        EOF
