name: 'Version matrix'
description: 'Generate a version matrix'

outputs:
  matrix:
    description: Generated version matrix
    value: ${{ steps.generate-matrix.outputs.matrix }}

runs:
  using: 'composite'
  steps:
      - shell: bash
        working-directory: .github/actions/version-matrix
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -r requirements.txt

      - shell: bash
        id: generate-matrix
        working-directory: .github/actions/version-matrix
        run: |
          echo "matrix=$(python3 build_versions.py)" >> $GITHUB_OUTPUT
