name: 'PR changed'

on:
  pull_request

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    steps:
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  rebuild:
    name: Build
    uses: ./.github/workflows/build-images.yml
    secrets: inherit
