name: 'Refresh PHP development containers'

on:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  rebuild:
    name: Build
    uses: ./.github/workflows/build-images.yml
    with:
      push: true
    secrets: inherit
